### PR TITLE
Ospray 2.10 for SCIRun

### PR DESCRIPTION
**Pull request by tpat95**
Rebased onto v2.10 and added build changes that were applied to the OSPRay 2.4 build for SCIRun. I've also tested this to pull and compile on the SCIRun master branch on my Linux machine.

### CODE REVIEW

**Comment by dcwhite** [comment]
@tarkpate Can we just merge this into a new `scirun-build-2.10` branch?

**Comment by dcwhite** [comment]
Then the conflicts just go away :)

**Comment by tpat95** [comment]
Yeah, that'd be perfect. I tried but Github doesn't let you create a PR onto a new branch

**Comment by dcwhite** [comment]
@tarkpate I created a branch that matches upstream's 2.10 release, and rebased this PR to that. So the diff is now much simpler.

**Review by dcwhite — APPROVED** [review]

**Pull request merged**
